const assert=require('node:assert/strict');
const make=require('./audit-harness.cjs');
const storage=new Map();const h=make(storage);h.pro();
h.run(`db=seed();db.animals=[{id:'e1',tag:'245',type:'Koyun',sex:'Dişi',status:'Aktif',breedingStatus:'Anaç'}];db.records=[{id:'b1',kind:'birth',motherId:'e1',date:'2026-09-12',count:2,label:'Doğum'},{id:'b2',kind:'birth',motherId:'e1',date:'2026-03-12',count:1,label:'Doğum'},{id:'i1',kind:'income',date:today(),amount:32000,label:'Kuzu satışı'},{id:'x1',kind:'expense',date:today(),amount:19600,label:'Yem alımı',category:'Yem'},{id:'old',kind:'income',date:'2020-01-01',amount:99999,label:'Eski gelir'}];renderAll();go('herd')`);
const before=h.run('JSON.stringify(db)');
assert(h.document.body.classList.contains('premium'));
assert.equal(h.document.querySelectorAll('.bottom .nav').length,5);
assert(h.document.getElementById('herdList').textContent.includes('1,5 kuzu / doğum'));
assert(h.document.getElementById('herdList').textContent.includes('2026-09-12'));
h.run(`animalCard('e1')`);assert(h.document.getElementById('modalBody').textContent.includes('2026-03-12'));h.run('closeModal()');
h.run(`openSub('finance')`);
assert(h.document.getElementById('subBody').textContent.includes('12.400'));
assert(!h.document.getElementById('subBody').textContent.includes('Eski gelir'));
assert(h.document.querySelector('[data-go="finance"]').classList.contains('active'));
h.run(`premiumFinanceMonth='2020-01';openSub('finance',true)`);
assert(h.document.getElementById('subBody').textContent.includes('99.999'));
h.run(`setAppearance('classic')`);
assert(!h.document.body.classList.contains('premium'));
assert(h.document.querySelector('[data-go="reports"]'));
assert(h.document.getElementById('subBody').textContent.includes('Eski gelir'));
assert.equal(h.run('JSON.stringify(db)'),before,'appearance toggle must not change herd or records');
assert.equal(storage.get('suru_takip_appearance'),'classic');
const reload=make(storage);assert.equal(reload.run('premiumAppearance'),false);
h.run(`setAppearance('premium');go('herd')`);
assert(h.document.querySelector('[data-go="finance"]'));
assert(h.document.getElementById('herdList').textContent.includes('1,5 kuzu / doğum'));
assert.equal(h.run('JSON.stringify(db)'),before);
console.log('PASS: new navigation, per-birth average and history, month-scoped finance, classic rollback, preference survives reload, data unchanged both ways');
