import assert from 'node:assert/strict';
import {applyOperation,readState,assertRole,checkClaims} from '../supabase/functions/flock-mcp/domain.mjs';
import {createHandler} from '../supabase/functions/flock-mcp/handler.mjs';
const base={animals:[{id:'ewe',type:'Koyun',sex:'Dişi',tag:'245',status:'Aktif',birth:'2024-01-01'},{id:'lamb',type:'Kuzu',sex:'Erkek',status:'Aktif',birth:'2026-01-01',weight:20}],records:[],stock:{Arpa:100},tasks:[]};
const user='u1',date='2026-10-03',resource='https://example.com/mcp',issuer='https://example.com/auth/v1';
const apply=(db,op,r='request001')=>applyOperation(db,op,r,user,date);
const birth={kind:'birth',date,animal_id:'ewe',sexes:['Erkek','Dişi']};
let c=apply(base,birth);assert.equal(c.state.animals.length,4);assert.equal(base.animals.length,2);assert.equal(c.record.count,2);
assert.equal(apply(c.state,birth).replayed,true);assert.throws(()=>apply(c.state,{...birth,sexes:['Erkek']}),/request_id_reused/);
assert.throws(()=>apply(c.state,birth,'request002'),/duplicate_birth/);
assert.throws(()=>apply(base,{...birth,date:'2026-02-30'}),/invalid_date/);
assert.throws(()=>apply(base,{...birth,date:'2027-01-01'}),/invalid_date/);
assert.throws(()=>apply(base,{...birth,animal_id:'someone-else'}),/invalid_animal/);
let w=apply(base,{kind:'weight',date:'2026-09-01',animal_id:'lamb',weight:40});w=apply(w.state,{kind:'weight',date:'2026-08-01',animal_id:'lamb',weight:30},'request002');assert.equal(w.state.animals[1].weight,40);assert.equal(w.state.records[0].previousWeight,30);
assert.throws(()=>apply(base,{kind:'weight',date,animal_id:'ewe',weight:40}),/lamb_required/);
c=apply(base,{kind:'expense',date,amount:500,category:'Yem'});c=apply(c.state,{kind:'income',date,amount:750,category:'Diğer gelir'},'request002');assert.equal(readState(c.state,{section:'finance',month:'2026-10'}).balance,250);
assert.throws(()=>apply(base,{kind:'income',date,amount:500,category:'Hayvan satışı'}),/invalid_category/);
c=apply(base,{kind:'sale',date,amount:5000,animal_ids:['lamb']});assert.equal(c.state.animals[1].status,'Satıldı');assert.equal(c.record.previousStatuses.lamb,'Aktif');assert.throws(()=>apply(c.state,{kind:'sale',date,amount:5000,animal_ids:['lamb']},'request002'),/invalid_animal/);
assert.throws(()=>assertRole('viewer',true),/forbidden/);assertRole('viewer');assert.throws(()=>assertRole('fake'),/forbidden/);
const claims={iss:issuer,sub:user,exp:Date.now()/1000+100,client_id:'client1',aud:resource,scope:'openid'};
checkClaims(claims,resource,issuer,['client1']);for(const patch of [{aud:'other'},{client_id:'other'},{exp:0},{scope:'email'},{iss:'other'}])assert.throws(()=>checkClaims({...claims,...patch},resource,issuer,['client1']));
const request=(name,args,token=true)=>new Request(resource,{method:'POST',headers:token?{Authorization:'Bearer test'}:{},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})});
let writes=0,role='viewer',member=true,version='v1';
function createClient(){return {auth:{getClaims:async()=>({data:{claims}}),getUser:async()=>({data:{user:{id:user}}})},from(table){let update=false;const q={select(){return q},eq(){return q},update(){update=true;return q},async maybeSingle(){if(table==='farm_members')return {data:member?{role}:null};if(update){writes++;return {data:{updated_at:'v2'}}}return {data:null}},async single(){return {data:{data:base,updated_at:version}}}};return q}}}
const config={url:'https://example.com',key:'public',resource,clientIds:['client1'],createClient,now:()=>new Date('2026-10-03T12:00:00Z')};
const handler=createHandler({...config,pilotUserIds:[user]});
assert.equal((await createHandler(config)(request('list_my_farms',{}))).status,403);
assert.equal((await createHandler({...config,pilotUserIds:['another-user']})(request('read_farm',{}))).status,403);
assert.equal(writes,0);
assert.equal((await handler(request('read_farm',{},false))).status,401);
const args={farm_id:'00000000-0000-0000-0000-000000000001',operation:birth,request_id:'request001',expected_version:'v1',confirmed:true};
assert.match(JSON.stringify(await (await handler(request('commit_farm_record',args))).json()),/forbidden/);assert.equal(writes,0);
role='owner';member=false;assert.match(JSON.stringify(await (await handler(request('read_farm',args))).json()),/forbidden/);member=true;
assert.match(JSON.stringify(await (await handler(request('commit_farm_record',{...args,expected_version:'stale'}))).json()),/version_conflict/);assert.equal(writes,0);
assert.match(JSON.stringify(await (await handler(request('commit_farm_record',{...args,confirmed:false}))).json()),/confirmation_required/);
const preview=await (await handler(request('preview_farm_record',args))).json();assert.equal(preview.result.structuredContent.saved,false);assert.equal(writes,0);
assert.equal((await (await handler(request('commit_farm_record',args))).json()).result.structuredContent.saved,true);assert.equal(writes,1);
console.log('Flock MCP: domain, isolation, consent, retry, chronology and concurrency checks passed.');
