const assert=require('node:assert/strict'),make=require('./audit-harness.cjs');
const a=make();a.pro();
const original=a.run('JSON.stringify(db)');
a.run("setAppLanguage('en')");
assert.equal(a.document.documentElement.lang,'en');
assert.match(a.document.querySelector('[data-go="home"]').textContent,/Home/);
assert.equal(a.run('JSON.stringify(db)'),original,'Language must not modify flock data');
assert.equal(a.storage.get('suru-language'),'en');
a.run('openAddAnimal()');
assert.equal(a.document.querySelector('#newAnimalType option').textContent,'Ewe');
assert.equal(a.document.querySelector('#newAnimalType option').getAttribute('value'),'Koyun');
a.fill('newAnimalType','Koyun');a.fill('newAnimalTag','EN-TEST');a.fill('newAnimalStatus','Aktif');a.fill('newAnimalBirth','2024-01-01');a.fill('newAnimalWeight','55');a.run('saveNewAnimal()');
assert.equal(a.run("db.animals.find(x=>x.tag==='EN-TEST').type"),'Koyun');
a.run("setAppLanguage('tr')");assert.match(a.document.querySelector('[data-go="home"]').textContent,/Ana Sayfa/);
a.run("setAppLanguage('en');openAdd('expense')");assert.equal(a.document.querySelector('#cat option').getAttribute('value'),'Yem');
assert.match(a.run("uiTranslate(handleLocalCommand('How much did I spend on feed this month?'))"),/Recorded feed/);
assert.equal(a.run("englishLocalCommand('Ewe 245 had twins; one male and one female')"),'245 2 kuzu doğurdu biri erkek biri dişi');
assert.equal(a.run("englishLocalCommand('Ewe 245 gave birth to four lambs')"),'245 4 kuzu doğurdu ');
assert.match(a.run("uiTranslate(handleLocalCommand('Ewe 245 gave birth to four lambs'))"),/between 1 and 3/);
assert.equal(a.run("englishLocalCommand('Ewe 245 gave birth')"),'Ewe 245 gave birth');
a.run("refreshLanguage()");assert.equal(a.document.querySelector('.userMsg'),null);assert.equal(a.document.getElementById('chat'),null);
const b=make(a.storage);assert.equal(b.document.documentElement.lang,'en');assert.match(b.document.querySelector('[data-go="reports"]').textContent,/Reports/);
console.log('PASS: language persistence, reversible navigation/forms, unchanged flock data, canonical select values, English commands and user-text protection');
