plugins { id 'com.android.application' }
android {
 namespace 'com.hasanlutfioglu.surutakip'
 compileSdk 36
 defaultConfig {
  applicationId 'com.hasanlutfioglu.surutakip'
  minSdk 24
  targetSdk 36
  versionCode 2
  versionName '1.0.1'
  testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
 }
 buildTypes { release { minifyEnabled false } }
}
dependencies {
 implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.3'
 implementation 'com.google.androidbrowserhelper:billing:1.0.0-alpha05'
 androidTestImplementation 'androidx.test:runner:1.6.2'
 androidTestImplementation 'androidx.test.ext:junit:1.2.1'
 androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
